# 要因計画と平均値差の検定その2 {#chapter22}

前回は要因計画が線形モデルの一種であること，また線形モデルを帰無仮説検定の枠組みで捉えるなら，横一線の全体平均だけの関数が帰無仮説に該当することを説明してきました。

今回も，帰無仮説検定と線形モデルの2つの枠組みを同時に眺めながら，検定結果の解釈やより複雑な計画の場合について見ていくことにします。

## 事後の検定

帰無仮説検定と線形モデルは同じものを別の角度から見ているに過ぎない，ということを説明してきていますが，私は個人的に，帰無仮説検定の方が面倒だなあと思います。いろいろ制約が多かったり，計算の手続きが煩雑だと感じています。線形モデルのままで，傾きの大きさを評価したらいいじゃないかと思うのですが，それはそれで数式が多くなって嫌になっちゃう人がいるかもしれません。分散分析の計算は，煩雑ですが手計算でもできますからね。

さて，今回も帰無仮説検定の枠組みの方から話をします。要因計画+統計的判断としての分散分析，ということで，帰無仮説(横一線モデル)と対立仮説(横一線ではないモデル全部)とのモデル比較でしたね。思い出して欲しいのですが，一要因3水準モデルの場合は，この対立仮説は次のうちの[どれか]{.ul}に該当している，ということでした。

-   $\mu_1 \neq \mu_2$だけど，$\mu_3$については$\mu_1=\mu_3$なのか$\mu_2=\mu_3$なのかわからない。

-   $\mu_1 \neq \mu_3$だけど，$\mu_2$については$\mu_1=\mu_2$なのか$\mu_3=\mu_2$なのかわからない。

-   $\mu_2 \neq \mu_3$だけど，$\mu_1$については$\mu_2=\mu_1$なのか$\mu_3=\mu_1$なのかわからない。

-   $\mu_1 \neq \mu_2 \neq \mu_3$，つまりとにかく全部違う

さて，分散分析の結果として「有意である」という判断がなされた，つまり帰無仮説が棄却されて対立仮説が採択されたとき，対立仮説のどれが成立しているんでしょうか。実は，これはわかりません。帰無仮説じゃないことが明らかになっただけですから。

じゃあどうするか。簡単に思いつくのは，上のいくつかの対立仮説サブモデルを，虱潰しに検証していくことです。すなわち，1群と2群，1群と3群，2群と3群というペアにして，対応のない$t$検定を3回やれば良いのでは，と考える方もいるでしょう。水準数が4つになると1-2,1-3,1-4,2-3,2-4,3-4の6ペア，5つになると1-2,1-3,1-4,1-5,2-3,2-4,2-5,3-4,3-5,4-5の10ペア・・・と水準数が増えれば手間は増えますが，なぁに機械が計算してくれるんだから努力で勝負！というところですね。

ですが，この考え方はこのままではうまく機能しません。というのも，帰無仮説検定は確率的な判断をすることですから，有意差があるというときに有意水準$\alpha$で誤り(タイプ1エラー)が含まれているからです。この確率的な判断を繰り返すと，実は困ったことが生じてきます。

例え話で考えてみましょう。ある腕利きの証券マンがいたとします。この人は目利きがよく，目をつけた株は大概値上がりするのです。もちろんたまに失敗はしますが，その確率は20回に1回だとしましょう。$1/20=0.05$ですから，失敗率が5%，顧客は彼に投資を依頼すると95%確率で儲けさせてくれる，とします。さてあるとき，彼に団体さんからの依頼が来ました。一度に10人分の依頼です。仮に別々の投資先を紹介しなければならないとして，95%の勝率をもっている彼は今回うまく全員を儲けさせることができるでしょうか？

この話の5%の失敗率(95%の成功率)というのは，もちろんタイプ1エラーの話です。本当は帰無仮説が正しい(差がない)のに，帰無仮説を棄却してしまう危険性と同じわけです。今回10人分の依頼があるというのは，いわば5水準の要因計画で各ペアについて検定を行うようなものですね。
1回の検定で正しく判断できる可能性は95%ですが，2回続けて正しく判断できる可能性は$0.95\times0.95=0.9025$です。これは$1-0.9025=0.0975$ですから，約10%にまで$\alpha$水準が上がっていることを意味します！同様に考えると，10人同時に勝負した時は，$1-0.95^{10}=0.4013$となり約4割の確率でどこかに間違った判断が紛れ込んでいることになります。

5%の危険率，95%の正しさであっても，確率的な判断ですから，繰り返すと意外と大きな数字に膨れ上がってしまう，ということになります。ですから，多くの水準があっても最初から$t$検定の繰り返しでいいじゃない，という考え方は適切ではありませんし，分散分析をして有意になってから追加の検定をするときも$t$検定の繰り返しではよくないのです。

ではどうすれば良いのか，ということになりますよね。この分散分析のあとの検定のことをとかといったりしますが，この事後検定については様々な方法が提案されており，どれが良い・悪いと一概には言えないところがあります(それだけで専門書一冊出ているぐらいで[@BA33892274])。とは言え，それでは困るでしょうから，2つほど方法を紹介しておきます。

##### Bonferroniの方法

さてここで問題になっているのは，基本的に$\alpha$レベルのインフレなのですから，これを低く調節してやれば良いのではないか，というのが1つの解決策です。例えば今回は3つの対立仮説があって，全部で5%水準を保ちたいわけですから，$0.05/3=0.017$として判断するようにしよう，というものです。これは直感的でわかりやすい基準ですね。この方法はさらにいろいろ改良版(Holm法，Shaffer
法，Holland-Copenhaver法)があります。

##### TukeyのHSD法

これが最も一般的で，よく使われている方法です[^1]。ここでは各対について別の統計量$q$を計算し，これが基準となるラインをクリアするかどうか，で判断します。

この他にも，統計パッケージによって様々な方法・オプションがあります。ですので，大事なのは「どの分析方法を使って，どのように判断したか」をしっかりと記録し，報告することだと思っておいてください。

そして何より，何度も繰り返しになりますが，これらの判断はいずれも「確率的に」「差の**有無**について判断する」ための技術だということを忘れないで欲しいのです。有無の判断はたくさんあるデータ・情報を1bitに落とし込んでしまいます。微細な差なのか重大な差なのか，「差があった」という報告だけでは伝わらなくなってしまいます。判断も確率的ですから，間違っている可能性もあります。下位検定も方法によっては差が検出できたりできなかったり，するかもしれません。だからと言って，差が出る方法を探す，というのは本末転倒なのです[^2]。それよりも差の大きさ，効果の大きさを直接評価したり，推定された母数がどのあたりにあるのかという区間を考えたりする方が，科学の実践という意味では重要です。

このセクションでは検定を繰り返すことについての問題点と，その回避策を説明しましたが，プロの学者による研究実践のなかでも，必ずしもこの問題点が重要視されてこなかったという歴史的経緯があります。今回は1つの分析の3つの水準という例でお話ししましたが，1つの論文の中に3つの実験をして，それぞれで$t$検定をしていても同じ「$\alpha$水準のインフレ」問題は生じます。複数の実験で現象を確認することは大事ですが，確率的な判断をしている以上，全体を通じて計画的に有意水準を設定しなければならないのです[^3]。しかし現実には，1つの研究についてたくさんの$t$検定を繰り返すとか，複数の実験を通じた$\alpha$水準の調整がなされてないことが少なくありません。残念ながら，これまで実際に「間違ったまま」研究が積み重ねられてきた実態があるのです。この問題は，一人一人が真剣に捉えないと，業界全体の危機になります。

帰無仮説検定は，正しく理解して使うためには，本来非常に専門的かつ繊細な技術が必要なのですが，その割りに機械が簡単に計算してくれてしまうので，間違った使い方が広まってしまっています。これに対抗するには，正しい知識を身につけるか，帰無仮説検定を使わなくするしかありません。帰無仮説検定で1bit判断をしなくてもよい方法があります。ひとつは信用区間や効果量といった大きさの報告に留めておくこと。もう1つはモーメント法による推定ではなく，確率モデルのベイズ推定を行うことなどです。後者の話題についてはこの授業の後半でまたお話しする機会があるかと思います。

一

## 帰無仮説検定としての二要因線形モデル

分散分析は，多水準の平均値差を検定する考え方です。二要因以上になると確実に3水準以上になりますから，分散分析の出番になります。帰無仮説検定の形式的手続きにのっとって，次のように考えましょう。

##### 仮説の設定

帰無仮説と対立仮説が必要です。既に述べたように，帰無仮説は母平均に差がないというものです。ここではどこをどう切り取っても母平均に差がない，ということになります。1つ目の要因の第一水準(温度要因のホット)で，2つ目の要因の第二水準(メーカー要因の銘柄B)の母平均を$\mu_{12}$とすると，帰無仮説は$H_0:\mu_{11}=\mu_{12}=\mu_{21}=\mu_{22}$ということになります。対立仮説はこの否定です。

##### 検定統計量を選択

平均値の推定ですが，分散を検定対象にするので$F$分布というものを使います。

##### 判断の基準になる確率を設定

有意水準$\alpha$，今回も5%で勝負を決めるとしましょう。

##### 検定統計量の実現値を計算

検定統計量$F$の実現値の計算は，先ほどの表[\[tbl::22_03\]](#tbl::22_03){reference-type="ref"
reference="tbl::22_03"}にある平方和を基に計算します。自由度を加味して1単位あたりの効果の大きさにしてから比べますので，分散分析表にまとめて表示しちゃいましょう。

::: {#tbl::22_04}
                  Df       SS       MS   F value     $p$
  ---------- ------- -------- -------- --------- -------
  温度         1.000    0.750    0.750     0.500   0.500
  メーカー     1.000    6.750    6.750     4.500   0.067
  交互作用     1.000   36.750   36.750    24.500   0.001
  誤差         8.000   12.000    1.500           

  : ANOVA Table
:::

[\[tbl::22_04\]]{#tbl::22_04 label="tbl::22_04"}

これをみると，温度の主効果はなく($F(1,8)=0.50,p=0.500$)，メーカーの主効果もなく($F(1,8)=4.50,p=0.067$)，交互作用がある($F(1,8)=24.50,p=0.001$)ことがわかります。今回各2水準ですので，主効果については事後検定をする必要はありません。交互作用がみられた場合は，どこに違いがあったのかさらに分析を進める必要があります。各水準ごとにデータを分割し(要因Aの第1水準，第2水準，要因Bの第1水準，第2水準)，その中でどこに差があるのかを探索します。今回の例で言えば，1.ホットの時に銘柄A/Bに差はあるか，2.アイスの時に銘柄A/Bに差があるか，3.銘柄Aにおいてホット/アイスで差があるか，4.銘柄Bにおいてホット/アイスで差があるか，の4パターンを検証することになります。もちろん検定の多重性の問題がありますから，Bonferroniや
Tukeyの方法などで補正する必要があります。

また，効果量も計算して報告するのが良いでしょう。これらの話は統計パッケージが自動的にしてくれることが多いので，Rの演習の時まで，細かい話はお預けにしておきます。

## 課題

[^1]: ただし「よく使われている」から「正しい」とか「優れている」というわけではありません。それぞれの方法に，それぞれの仮定・前提，注目するところ・強調するところなどが変わって来ますし，「よく使われる」というのは実質的に「よく使う統計ソフトパッケージがこの統計量を計算してくれる」ぐらいの意味しかないこともあるからです。

[^2]: この悪しき実践法はp-hackingと呼ばれます。

[^3]: 一回の分析あたりの$\alpha$水準のことを，ファミリーワイズfamily-wiseの$\alpha$といい，1つの論文あたりの$\alpha$水準のことを，エクスペリメンタルワイズexperimental-wiseの$\alpha$といいます。
