# データ生成モデリング {#chapter17}

## データ生成モデリング {#データ生成モデリング}

「心理学統計法」と名のつく講義のほとんどは，記述統計や推測統計，得に帰無仮説検定を扱うことが中心であるのが現状です[^1]。心理学において帰無仮説検定を行う理由は，心理学実験の効果を検証すること，それも手元の標本についての記述ではなく母集団においてもその効果があると言えるかどうかを検証するためです。手元のデータに基づいて，目に見えない母集団全体のことに推論するというのは，基本的に不良設定問題です。つまり，確実な正解を導き出すにはヒントが少なすぎる，圧倒的に不利な状況で知恵を絞る必要があるのです。こうした不利な状況下ですから，いくつかの仮定をおいて，確率的に推論するのでした。その推論の方法として，，，があるのでした[^2]。

これらの推定方法が(要因計画ともいう)と組み合わせで用いられ，帰無仮説検定となるのでした。心理学における実験的なアプローチは，実験群と統制群に無作為に割り当てた集団に対し，介入・処置のあとでの群平均を見ることでその効果を検証します。人間を相手にする研究ですから，当然誤差や個人差がデータには含まれますが，無作為割り当てと平均化によってそれらはキャンセルアウトされ，平均の比較をすることで効果を見ることができると考えるのでした。また標本の平均ではなく，それを用いて母平均を推測することで，結果の一般化を考えます。母平均の推定には点推定と区間推定とがあり，確率的表現を用いた区間推定をつかって慎重に結論を導き出すのです。ただし区間推定は判断基準が明確ではありませんから，帰無仮説と対立仮説という2つのモデルを戦わせて決着を見る，というやり方をして一応の決着を見るのでした。こうした「実験計画」+「推測統計学」＝「帰無仮説検定」は，長らく心理学のスタンダードとして君臨しています。

こうしたアプローチについて，昨今批判があることについては，今は触れないでおきましょう[^3]。それよりもこうした問いの立て方や解決策に注目してみたいと思います。心理学は物理学を範として，科学scienceの仲間入りをしたい，というモチベーションが強く根付いている世界であり，また人間というのは嘘をついたり間違えたりするものだ，ということが骨身に染みてわかっていますから[^4]，データを分析する際にもを大事にすることが殊更重視されます。客観性の反対は主観性，つまり本人の思い込みや考え方の癖がもっとも邪魔になるのです。そこでデータに対しては真っ白な気持ちで向き合うものだ，という姿勢をとることになります。

言い方を変えると，分析をする前はデータについて何も考えてないよ，という態度をとるわけです。もちろんデータは要因計画の結果として得られるものですから，計画を立てる際は主観的な誤謬が微塵も入り込むことないように緻密に練り上げるのですが，出てきた結果は結果，数字の羅列に過ぎないと考えるのです。その結果を統計的に分析するときは，それが記憶実験の数字であろうが臨床実験の結果であろうが気にすることはなく，淡々と帰無仮説検定の俎上に乗せていくことになります。こうしたアプローチができるからこそ，そしてそれを許す統計ソフトウェアがあるからこそ，心理学の研究を積み重ねていくことができたのだという一面があります。こうした研究アプローチは，データ駆動型分析と言えるでしょう。つまりデータができてから，分析が始まるという考え方です。

これに対して，データがどのように生まれてきたのか，そのメカニズムを考え，その仕組みを明らかにしていこうというのがデータ生成モデリングです。@松浦201610は統計モデリングを「確率モデルをデータに当てはめて現象の理解と予測を促す営みのこと」と定義しています。すなわちこのアプローチは，まずデータがどのようなメカニズムで生まれてきたのかを，簡潔な数式を使って表現します。そのモデルをデータに当てはめ，このモデルからデータが出てきたと言えるかどうか，他のモデルの方が今のデータをうまく説明するのではないか，といった比較検証をしていくことになります。データ駆動型分析では，こうしたメカニズムが実験計画の中に暗黙理に埋め込まれていたと言えるかもしれません。データ生成モデル駆動型の分析は，メカニズムを明示して検証する，というところが違います。

データが作られるメカニズムを考えるアプローチの利点は，予測にも向います。メカニズムが正しい，あるいはうまく現状のデータを再現できるのであれば，おそらく今後も同じようにデータが作られていくでしょう。であれば将来の予測ができる，という考え方です。たとえば市場の動向の予測，消費者の傾向の予測ができればそのメリットは想像に難くありません。昨今はデータサイエンスという言葉が流行していますが，そこにはこうした研究アプローチの隆盛があるのです。もちろん，心理学においてもモデリングのアプローチは有用ですし，従来通りの平均値の比較をする上でも，様々なメリットがあります。

この授業では，データ生成モデリングのアプローチをとって，心理学的にもどういう意義があるのかを考えていきましょう。

これを考える上で重要なのがです。言葉の通り，データ生成過程を確率を使って表現します。なぜ確率を？と思うかもしれませんが，手元のデータは誤差や個人差を含んで微小に変わる，偶然の成分が必ず入っているからです。こうした偶然をハンドリングし，偶然の中にも理論的な予測をするという点で確率が必要になるのです。また確率モデルで考えるときに，最尤法よりもベイズ法の方がよく使われます。確率モデルが複雑になっていくにつれ，最尤法では計算コストが非常に高く，実質的に解が得られないということも少なくありません。ベイズ法によるアプローチはこの問題をクリアしてくれるからです。それでは改めて，ベイズ法について復習しておきましょう。

## ベイズ推定の基礎

データ生成モデルが確率の言葉で記述される，というのは既に述べたところです。推測統計というのがそもそも不良設定問題，すなわち少なすぎるヒントから未知なるものを当てるという状況に置かれた学問であり，この「わからないこと」を確率で表現するからです。この確率についての考え方として，ベイズの公式というのがあるのでした。ベイズの定理は次のように書き表されます。

$$P(\theta|D) = \frac{P(D|\theta)P(\theta)}{P(D)}$$

ここで$P(X)$はXについての確率，という表現です。$P(A|B)$は条件付き確率というもので，Bが与えられた時のAの確率，という意味です。

ベイズの定理の用語は次の通りです。まず右辺の分子に注目しましょう。$P(D|\theta)$とありますが，ここで$D$はデータを表しています。$\theta$はデータを生む確率のパラメータです。$P(D|\theta)$はパラメータ$\theta$のもとでのデータ$D$が得られる程度を表すもの，という意味になります。これはと呼ばれるもので，パラメータの関数になっているのでした。たとえば正規分布からデータが生成されると考えるのであれば，手元のデータがパラメータ$\theta$から出てくる可能性がどれぐらいあるのか，を表現していると言えるわけです。この尤度関数は，データを生み出すメカニズムの表現そのものです。

右辺の分子の第二項，$P(\theta)$はパラメータの確率です。正規分布からデータが生成される例で言えば，尤度はあるパラメータの値からデータが得られる程度を表現しているのですが，そのパラメータが出てくる確率はそもそもどの程度であるか，を考えているのです。これは別名とも呼ばれます。実際にデータが出てくる前の段階で，そもそもそのパラメータがどれほど出やすいかという確率を表現しており，これは今回のデータを取る前までの事前のデータや経験に基づいている，ということができます。

右辺の分母，$P(D)$はデータ全体が得られる確率であり，とかと呼ばれます。ということもあります。これについては理解しにくいところもあるかもしれませんが，後に述べる理由によって，ひとまず深く考える必要はありません。

左辺はこの計算の結果得られるを表しています。$P(\theta|D)$はデータ$D$で条件づけられたパラメータ$\theta$の確率です。我々は確率モデルを作るわけですが，そのパラメータがどうなっているかは事前にはわかりません。が，データを取ることで「データが与えられたのであれば，パラメータはこうだよ」というのがわかるわけです。あるいは事前にパラメータはこのあたりにあるのではないか，と経験上考えていたとしても，それがデータを取ることによって更新される(確信が強くなったり，違うかもしれないと思い直したり)，ということを意味しています。

この式を言葉で表現し直すと，次のようになります。

$$\mbox{事後分布} = \frac{\mbox{尤度}\times \mbox{事前分布}}{\mbox{周辺尤度}} = \mbox{尤度} \times \frac{事前分布}{周辺尤度}$$

がメカニズムそのものだ，ということは既に書きました。たとえば回帰分析においても，尤度を計算できます。普通の回帰分析は，誤差が確率的に生じると考え，御災害のところは線形モデルで表現します。すなわち，従属変数$Y_i$に対して，独立変数$X_i$があったとすると，

$$\begin{array}{lll}
        Y_i &=& \hat{Y}_i + e_i = \beta_0 + \beta_1 X_i + e_i\\
        e_i &\sim&  N(0,\sigma)\\
    \end{array}$$ より， $$Y_i \sim N(\beta_0 + \beta_1 X_i, \sigma)$$
となるのでした。ここで$N(\mu,\sigma)$は平均$\mu$，標準偏差$\sigma$の正規分布を表し，データ$Y_i$が正規分布から生成されているというモデルになっています。回帰分析の場合はで未知数$\beta_0,\beta_1,\sigma$を求めたりしましたが[^5]，その名の通りこのモデルが示す尤度を最大にする未知数の求め方を最尤法というのでした。

ですが，尤度は確率を表すものではありません。確率とは非負の実数で，全ての確率を足し合わせる(あるいは積分する)と$1.0$にならなければなりませんが，尤度は足し合わせても1.0にならない数字なのです。ですから，「手元のデータがパラメータからでてくる**可能性**」という変な言い回しをしていました。「出てくる**確率**」とは言えないのですね。そこで，尤度を確率に置き換えたい，と考えたときに便利なのがベイズの定理なのでした。ベイズの定理は尤度に事前分布をかけ，周辺尤度で割るという操作によって，事後分布が得られる式，と読むこともできます。[事後分布は確率分布です]{.ul}。尤度にある数字をかけて(事後の)確率分布にしていると考えるといいでしょう。
ちなみに事前分布も確率分布ですが，は確率ではありません。たとえば度数を総度数で割った相対頻度は確率と考えることができますが，それと同じように，分子をとある数字で割って，全体を1.0に整えるための定数なのです。というのはそういう意味ですね。定数倍(正確には定数の逆数)をかけて大きさの調整をしているだけですので，ベイズの式はさらに次のように書き直すことができます。

$$\mbox{事後分布} \propto \mbox{尤度}\times \mbox{事前分布}$$

ここで$\propto$は比例する，という関係を表しています。最終的には事後分布の形が知りたいのですが，その形を決めているのは分子の尤度と事前分布だけだ，ということになります。

ここで事前分布がであれば，事後分布の形状には影響せず，事後分布は尤度そのものの形を反映することになります。従来のデータ駆動型分析では，データに対して事前の仮定を一切置かないということでしたが，ベイズ流の分析でもそのことは同様に表現できるわけです。

以上がベイズの定理についての簡単な復習でした。しかしベイズの定理自体は，1740年代には明らかになっていたことであり，それがなぜ21世紀の今になって見直されてきたのでしょうか。それには色々な理由がありますが，その1つは最近まで「ベイズ流の分析は絵に描いた餅」だったからです。すなわち理屈ではこのような形になることは明らかだったのですが，実際に計算するのは難しいことが多々ありました。その問題を解決したのがと呼ばれる方法です。

## マルコフ連鎖モンテカルロ法

ベイズの定理から，事前分布と尤度が分かれば，計算式を解いて事後分布の形を算出できます。しかし確率分布の指揮が複雑になればなるほど，その計算はとても難しくなります。確率関数を複数組み合わせたり，求めるべきパラメータの数が増えて行ったりすると，とてもじゃないけど計算して答えを出すことができない，ということになります。そのせいもあって，ベイズ統計学は長らく実践には向かない手法だったのですが，，略してが出てきてからその状況が一変しました。

MCMC法は近似的な答えを探す1つの方法です。MCMCという名前は「マルコフ連鎖」と「モンテカルロ法」の2つのパートから出来上がっています。マルコフ連鎖は，目標となる確率分布状態になるような推移規則を作る方法であり，モンテカルロ法は乱数を発生させるアルゴリズムです。この2つが合体することで，確率分布の形がわからなくてもサンプルが得られるような，乱数発生器を作る方法，ということになります。

ベイズ統計のゴールは事後分布を作ることです。事前分布を一様分布にして，尤度はベルヌーイ分布にする，といった簡単な場合ですと特に問題ないのですが，ある確率分布のパラメータがあって，さらにそれを生成する確率分布があるといった，階層的に入れ子になっているようなモデルが出てくると，「最終的な事後分布の形がわからない」という状況になります。正規分布とかポアソン分布といった，名前がついている確率分布であればその特徴がはっきりわかるのですが，それらを組み合わせて作られるものは名もなき合成関数になり，どんな形状をしているのか，全く想像つかないことがあります。マルコフ連鎖を使うと，そのなもなき合成関数の形状をとにかく作り上げることができる，そんな数学的技術です。

モンテカルロ法は乱数発生技術です。乱数というのは規則性のない数ですが，これを作るのはなかなか難しいものです。人間が0-9の数字を適当に書いていくと，知らず知らずのうちに均等でないパターンができてしまいます[^6]。コンピュータに(例えばRに)乱数があるじゃないか，と思われるかもしれませんが，コンピュータはあくまでも計算機でどこまでも合理的です。乱数によって動いているように見えますが，乱数に見えるような数字を生成するアルゴリズムがその中には埋め込まれていますから，正確には擬似乱数でしかありません。コンピュータの作る乱数は，もちろん人間が適当に思いつく乱数よりもより規則性が少ないですが，それでも基本的に

-   何らかの関数$g$によって，内部状態$S_t$をアップデートする；$S_{t+1}=g(S_t)$

-   内部状態$S_t$から何らかの関数$h$によって，実現値が生成される；$x = h(S_t)$

というステップを反復($t=1,2,3\ldots$)することで生成するのです。こうした乱数列ができれば，それを正規分布の形だとか二項分布の形に当てはめて出力することは簡単なのです。このステップ・バイ・ステップの計算法としてある確率分布に従う乱数発生技術があり，これがマルコフ過程とひっついてできたのがMCMC法ということになります[^7]。

MCMC法は，ですから，どんな形の確率分布であっても乱数のサンプリングは生成できる，という技術なわけです。事後分布の関数の形，形状がわからなくてもそこからの乱数は作れるという技術であり，コンピュータ技術の性能が発展した今では大量の乱数を生成することも瞬時に行われます。

乱数を用いるアプローチはいくつかの利点があります。たとえば確率分布の平均である期待値など，分布の特徴を記述するための計算は積分を含むので解析的に解くのは知識も技術も必要です。しかしその確率分布から乱数を発生させると，その平均値を求めることでその近似値を得ることができます。確率分布の計算が記述統計の計算に置き換えられるのであり，また統計ソフトウェアにとって大量のデータの記述統計量を描くのは造作もないことなのです。乱数による近似値は，あくまでも近似値，近くて似ている値に過ぎませんが，精度を上げるためにはその乱数の数を増やしてやるだけで良いことになります。この点もいいですね。

また求めたいパラメータが複数ある場合，たとえば正規分布だと平均と標準偏差が未知数ですし，回帰分析では平均の中に切片と傾きといった未知数が入っているわけですが，このような場合の事後分布は同時確率空間ということになります。すなわち平均と標準偏差という2つの変数の場合でも，可視化するなら3次元空間が必要です(x軸に平均，y軸に標準偏差，z軸に確率密度)。こうした多次元空間において，あるパラメータだけについて期待値を計算したい，という場合はそれ以外のパラメータについては**周辺化**といって積分して全部の可能性をつぶしてしまう必要があるのですが，この計算も解析的にやるには実に大変なものです。しかし多次元の事後分布空間から生成された乱数があるなら，注目したい変数だけについての記述統計をすれば，他の変数を周辺化したこと同じになります。なんと便利なのでしょう。

このように，乱数を使ったアプローチは計算上非常に有利な特徴を揃えています。乱数を大量に発生させられるような計算機のパワーは，最近のPCでしたら十分持っていますから，最近になってベイズ統計学やモデリングアプローチが生きてきたわけですね。さらにありがたいことに，事後分布から乱数を発生させるためのプログラミング言語ツールが登場したのも大きいでしょう。古典的にはBUGSというソフトウェアが，最近ではJAGSやStanといったのがそれで，と呼ばれたりします。これらの言語では，尤度と事前分布をモデルとして表記し，それにデータを与えてやることで，事後分布からの乱数を生成します。いわば万能乱数発生器なのです。こうした環境が整ったことで，簡単に分析できるようになりました。

## 乱数によるアプローチの例

それではMCMCを使った実践に入る前に，乱数を使って何ができるのか，Rで確かめてみましょう。

### 乱数による近似の例

まずは馴染み深いの例からいきましょう。

正規分布に感するRの関数は`dnorm,pnorm, qnorm ,rnorm`などがあります。この`d,p,q,r`は他の確率分布を表す関数の前につける接頭語で，`d`は確率密度，`p`は累積確率,`q`はある累積確率になるときの確率点，そして`r`が乱数発生を意味しているのでした。

``` {#code::17_01 .c++ language="c++" label="code::17_01" caption="乱数のコードの例"}
rm(list = ls())
set.seed(12345)
dnorm(0, mean = 0, sd = 1)
pnorm(0, mean = 0, sd = 1)
qnorm(0.6, mean = 0, sd = 1)
rnorm(10, mean = 0, sd = 1)
set.seed(12345)
rnorm(5, mean = 0, sd = 1)
```

##### コード解説

1行目

:   環境の初期化

2行目

:   乱数発生開始点の設定

3行目

:   標準正規分布の，確率点$x=0$における確率密度の計算

4行目

:   標準正規分布の，確率点$x=0$までの累積確率

6行目

:   標準正規分布の，累積確率60%になるときの確率点

7行目

:   標準正規分布から乱数を10個出力する

8行目

:   乱数発生開始点の再設定

9行目

:   標準正規分布から乱数を5個出力する

このコードを使って確認しておいて欲しいところは，3つあります。まず`d,p,q,r`をつけたときの意味です。それぞれ正規分布のどういう数字を返しているのか，しっかり確認しておいてください。
次に7行目にある乱数の発生です。これを実行すると，標準正規分布にし違う乱数が10個出力されます。乱数ですので，数字の並びに規則性はありません。バラバラの数字が出ていることを確認してください。
最後に8行目，9行目の内容です。8行目は2行目と同じく，乱数の開始点を定めています。Rで出力される乱数は，規則性がない数字とは言え，計算によって算出している数字ですから規則性は拭いきれず，再現してしまいます。どこから計算を始めるか，という開始点はと呼ばれ，ここに入力した数字が開始点になります。シード値の設定に特に意味はなく，好きな数字にしていただいて結構です。ポイントは，任意の数字であっても同じ数字に設定すると，乱数はそこから計算して算出されますので，9行目で実行した5つの乱数は7行目の最初の5つと同じ数字が再現されているというところです。
規則性のない数字なので再現されては困ると思うかもしれませんが，科学計算のアプローチという意味では再現性が担保できることも重要なのです。

では乱数を使う例をもう少し見てみましょう。次はについて考えてみたいと思います。これはコイントスをして表が出るか，裏が出るかという0/1の離散的結果を生み出す分布です。
残念ながらRにはベルヌーイ分布の関数はなく[^8]，二項分布の特殊例として使うことにします。とは，N回コイントスをしてK回表が出る確率を表す分布ですが，これのコイントス回数が1回であればベルヌーイ分布と同じことになります。

``` {#code::17_02 .c++ language="c++" label="code::17_02" caption="乱数のコードの例2"}
rbinom(10, size = 1, prob = 0.5)
rbinom(10, size = 1, prob = 0.3)
rbinom(10, size = 1, prob = 0.7)
# パッケージの利用
library(extraDistr)
rbern(10, prob = 0.5)
```

##### コード解説

1行目

:   二項分布の乱数を10個発生させる。確率は0.5で。

2行目

:   二項分布の乱数を10個発生させる。確率は0.3で。

3行目

:   二項分布の乱数を10個発生させる。確率は0.7で。

4-6行目

:   `extraDistr`パッケージによるベルヌーイ乱数例

ここで確認して欲しいのは，コイントスを10回するとして，確率0.5の場合はほぼ半々，0.3の場合は半分以下，0.7の場合は半分以上表($1$)が出ている，ということです[^9]。ここで確率を幾つにするかは，われわれが自由に設定できます。また乱数を幾つ発生させるかも自由です。これらの数字を色々変えて遊んでみましょう。

たとえば乱数の数を100回，1000回，10000回と増やしたとします。その結果を全て表示するのは大変ですが，その平均値を計算してみるとどうなるでしょうか。

``` {#code::17_03 .c++ language="c++" label="code::17_03" caption="乱数のコードの例3"}
N100 <- rbinom(n = 100, size = 1, prob = 0.5)
N1000 <- rbinom(n = 1000, size = 1, prob = 0.5)
N10000 <- rbinom(n = 10000, size = 1, prob = 0.5)
mean(N100)
mean(N1000)
mean(N10000)
```

##### コード解説

1-3行目

:   二項分布の乱数を100個，1000個，10000個発生させる。確率は0.5で。

4-6行目

:   それぞれの平均値を計算する

これの実行結果は，私の環境では出力[\[RS:out17_01\]](#RS:out17_01){reference-type="ref"
reference="RS:out17_01"}のようになりました。

::: Rscreen
乱数出力の結果out17_01

    > mean(N100)
    [1] 0.62
    > mean(N1000)
    [1] 0.52
    > mean(N10000)
    [1] 0.5003
:::

もともと確率を`prob = 0.5`と設定しましたから，理論的には0.5，つまり半々の確率で表($1$)が出たり裏($0$)が出たりするはずですが，最初の100回では62回なのでやや表が多めに出たようです。乱数ですので，そういうことはあります。ただ，この傾向も，1000回，100000回と繰り返していくと，ほぼ偶然による偏りはなく，半々の比率になっていくのが確認できると思います。このように，乱数が十分多ければ，確率分布の近似値として使うことができるというわけです。

ちなみに今回は平均をとりましたが，これは確率分布のを計算したこと同じになります。

### 乱数を用いた確率分布のプロット

乱数を使って近似できる，という例を可視化で見てみましょう。また正規分布を例にしてみたいと思います。

``` {#code::17_04 .c++ language="c++" label="code::17_04" caption="確率分布の可視化1"}
x <- seq(-4, 4, 0.05)
plot(x, dnorm(x))
library(tidverse)
ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dnorm)
```

##### コード解説

1行目

:   -4から4までの範囲で，0.05刻みの数列を作る

2行目

:   低水準プロット。各確率点の確率密度をプロットする

3行目

:   パッケージの読み込み

4-5行目

:   `ggplot`による美しい描画。`stat_function`は関数の結果を図にするもの

これは理論的な正規分布の形を図示するものです。美しいですね。でも同様のことが，乱数を使ってもできます。

``` {#code::17_05 .c++ language="c++" label="code::17_05" caption="確率分布の可視化2"}
N <- 1000
X <- rnorm(N, mean = 0, sd = 1) %>% as.data.frame()
ggplot(data = X, aes(x = .)) +
  geom_histogram()
```

##### コード解説

1行目

:   発生させる乱数の数

2行目

:   乱数を発生させ，`data.frame`型に組み上げる

3-4行目

:   `ggplot`による美しい描画。`geom_histogram`になっているところに注意

このコードの結果描かれるカーブは，それほど美しいものではないかもしれません。しかし発生させる乱数の数が増えればどうでしょうか。どんどん形が似ていくことがわかると思います。
ここでのポイントは，ヒストグラムを描いたらその稜線が確率分布の形になること，乱数の数が増えれば十分な近似になることです。よく確認しておいてください。

### 乱数を用いた確率分布の要約

最後に，確率分布の特徴を記述するコードの書き方について練習しましょう。
乱数発生によるアプローチは，記述統計量で確率分布の特徴を記述できます。確率分布の期待値は，その算術計算の平均で良いのですが，中央値やパーセンタイル，分散や標準偏差も分布を記述する重要な指標です。
さらに確率分布における，確率密度が最も高くなる点は，「最も生じる確率が高い点」という意味で重要ですが，それを求めるためには特別な関数を書く必要があります。

まずは`data.frame`型にした正規乱数を使って，記述統計量を算出する例を見てみましょう。

``` {#code::17_06 .c++ language="c++" label="code::17_06" caption="確率分布の要約"}
N <- 10000
X <- rnorm(N, mean = 0, sd = 1) %>%
  as.data.frame() %>%
  dplyr::rename(val = 1)
X %>%
  summarise(
    Exp = mean(val),
    SD = sd(val),
    Median = median(val),
    U50 = quantile(val, prob = 0.50),
    U90 = quantile(val, prob = 0.90),
    L90 = quantile(val, prob = 0.10)
  )
```

##### コード解説

1行目

:   乱数を10万個作ることにします。

2行目

:   標準正規分布の乱数発生

3行目

:   データフレーム型に整形

4行目

:   変数名がつけられていないので，`val`という名前をつけることに。ここでの$1$は1列目を意味している。

6行目から

:   データフレーム`X`を使って計算

7行目

:   `summarise`関数は要約計算。変数名$=$計算式で表す。

8行目

:   期待値を`mean`関数で算出

9行目

:   確率分布の標準偏差を`sd`関数で算出[^10]

10行目

:   中央値を`median`関数で計算

11-13行目

:   パーセンタイル点を算出。50パーセンタイル点は中央値に同じ。

また，確率密度が最も高くなる点を算出するための関数を自分で作ってみることにします。次のようにコードを入力してください。

``` {#code::17_07 .c++ language="c++" label="code::17_07" caption="確率分布の要約"}
map_estimation <- function(z) {
  density(z)$x[which.max(density(z)$y)]
}
# 試してみる
X %>%
  summarise(
    MAP = map_estimation(val)
  )
```

##### コード解説

1行目

:   関数の宣言。`map_estimation`という関数名を作る。この関数は引数$z$を取る

2行目

:   `density`関数は与えられた数列の関数を考え，そのカーネル密度を計算します。`which.max`関数はその中でも最も密度の高い値を返すものです。

3行目

:   関数の終わり

5-8行目

:   先程の例で試してみる。

このようにして，確率密度関数の近似値が簡単な関数で求められます。

次回以降は，モデルに基づいて計算された事後分布から得られる乱数について，これらの関数を使ってその特徴を記述していくことになります。
関数や指標の意味をしっかりと理解しておいてください。

## 課題

次の計算をするRコードを記述し，提出してください。提出はRスクリプトファイルでもRmdファイルでも構いませんが，どの課題に対するコードなのかがわかるよう，コメントや説明文を記入しておくこと。なお提出されたコード単体でバグがなく動くことが確認できないものは，未提出扱いになります。コードの書き方などわからないところがあれば，曜日別TAか小杉までメールで連絡し，指導を受けてください。

1.  平均50，標準偏差10の正規分布に従う乱数を10万点生成し，その平均値，中央値，標準偏差，15パーセンタイル，75パーセンタイル，2.5パーセンタイル，97.5パーセンタイルを算出してください。

2.  先程求めた正規乱数の記述統計量が，理論値の近似値になっていることを確認します。`dnorm,pnorm,qnorm`などを使って理論値を算出してください。

3.  正規乱数のデータセットのうち，30以上60未満の値が含まれる割合を計算してください。またそれが理論値の近似値になっていることを確認するため，`dnorm,pnorm,qnorm`などを使って理論値を算出してください。

[^1]: 特に公認心理士に必要な授業として，科目名「心理学統計法」を名乗る必要があり，そこで教える基本的な内容としてこれらが含まれています。なお測定論やそれに関する多変量解析法はそれほど中心的話題ではありません。みんな使うのになあ。

[^2]: これら三つの方法について，十分に思い出せない人は一年時の授業資料を振り返ってみてください。

[^3]: @amrhein2019scientistsなどが指摘するように，誤った使い方をされることが多く心理学研究の意義そのものが疑われるほど担っている現状があります。また@豊田202003ではさらに辛辣に批判がなされています。

[^4]: というか心理学の研究というのは，いかに人間がダメで偏った考え方をする生き物であるかを，滔々と明らかにしていくという側面もあります。

[^5]: あるいはで求めるのですが，これは幸い最尤法の結果と一致します。正規分布を使った線形回帰モデルの場合，データの記述統計的値と確率モデルによる推定値が一致するので，気づかないまま推測統計学に足を踏み入れてしまえるのでした

[^6]: 嘘の538(ゴサンパチ)という標語があって，人間がふと思いつきで数字を作ろうとすると5，3，8が多くできてしまうと言われています。エビデンス(出典)がわからないので本当かどうかわかりませんが・・・。

[^7]: 余談ですが，スマホアプリなどで「ガチャを引く」というのも内部では乱数が生成されていて擬似的に「偶然あたりが出た」のを装っているに過ぎません。私はゲームなどをする時，擬似乱数に思いを馳せ「どこかの誰かに遊ばされている」と思うとやる気がなくなるので，ガチャを引くようなシーンは興醒めしてしまいます。やはりマルチプレイヤーゲームのように，人間が背後にいたほうがよっぽど意外な行動が見られますし，ゲームよりもリアルの世界の方が擬似的でない本物の偶然を楽しむことができて面白いと思います。皆さんはどうお考えですか。

[^8]: `extraDistr`パッケージを用いると，`bern`という関数名でベルヌーイ分布が使えます。

[^9]: 正確には二項分布なので，1が出た回数が出力されているのです。試行数(`size`)を1にしているので，1回中1回表が出た＝表($1$)が出た，と解釈しても，結果的に同じことであるというだけです。

[^10]: Rの`sd`関数は不偏標準偏差を計算しており，厳密には標本標準偏差の計算で良いが，サンプルサイズが十分に大きいのでほとんど影響しません。
