# Rをつかっての行列計算 {#chapter9}

## Rによる行列計算

今回は統計環境Rをつかって，演習によってこれまで習ったことを整理していきましょう。

### 環境の準備(確認)

まずは環境の準備です。既にRやRStudioのインストールは終わっているものとして話を進めます[^1]。次の3つのステップをたどって，実行の準備をしてください。

##### RStudioの起動

RStudioを起動してください。パッケージのインストールをするときなど，管理人権限が必要になるケースがあります。

##### プロジェクトを開く {#UnderProject}

RStudioを使う時の基本は，プロジェクトによる管理です。分析するデータ、テーマ、内容によってプロジェクトを切り替えながら使います。メニューバーから`File > New Project`と進んでください。すると「New
Directory」「Existing Directory」「Version
Control」の選択肢が出てきます。New
Directoryは新しいディレクトリ(=フォルダ)を作ってそこで関連ファイルをまとめますよ，という意味です。Existing
Directoryは既に存在するディレクトリ(=フォルダ)をまとめる場所にしますよ，という意味です。みなさんの環境に応じて使い分けてください。既にプロジェクトが存在する場合は，プロジェクトを開く(FIle$\to$Open
Project)から選択します。RStudioの右上などで，プロジェクトが開いていることを確認しましょう。

##### Rスクリプトを開く

今日のコードを書くためのRスクリプトファイルを準備します。File \> NewFile
\> R
Scriptと進み，何も書いてないRスクリプトの画面を表示させてください。真っ白いファイルが開いたら問題ありません。

これでスクリプトのところにコードを書いていく準備ができました。

### Rにおけるデータの型

統計環境RはExcelやNumbersやCalcsなど[^2]の表計算ソフトとは違って，データを行列・ベクトルとして扱うことができます。例えば次のコードを実行してみてください。

``` {#code::09_01 .c++ language="c++" label="code::09_01" caption="ベクトルデータの保持"}
A <- 1:9
B <- c(3, 4, 5)
C <- matrix(A, ncol = 3)
D <- matrix(A, ncol = 3, byrow = T)
```

##### コード解説

1行目

:   `1:9`をオブジェクトAに代入しています。ここでコロン`:`は連続した数字を表しており，`c(1,2,3,4,5,6,7,8,9)`と同じ意味です。

2行目

:   要素$3,4,5$からなるベクトルを作ってBに代入しています。`c()`は結合する(combine)という関数です。

3行目

:   9つの要素があるベクトルを持ったオブジェクトAを`matrix`型に変更しています。その時の列数は3(`ncol=3`)です。

4行目

:   同じくオブジェクトAを`matrix`型に変換，列数は3ですが`byrow = T`で「行ごとに並べる」スイッチをオン(TRUE)にしています。

それぞれのオブジェクトに格納されているものを確認してみましょう。何がどうなっているか分かるでしょうか(出力[\[RS:out09_01\]](#RS:out09_01){reference-type="ref"
reference="RS:out09_01"})。

::: Rscreen
Rにおけるベクトルと行列out09_01

            > A
            [1] 1 2 3 4 5 6 7 8 9
            > B
            [1] 3 4 5
            > C
                 [,1] [,2] [,3]
            [1,]    1    4    7
            [2,]    2    5    8
            [3,]    3    6    9
            > D
                 [,1] [,2] [,3]
            [1,]    1    2    3
            [2,]    4    5    6
            [3,]    7    8    9
:::

Rのオブジェクトには色々な型がありますが，基本はベクトルです。数字のセットとして扱うのです。このときのRのベクトルに行・列の区別はありません。
行列であることを明示するためには，`matrix`という関数を当てはめることになります。ベクトルに行，列の意味を持たせたければ，`matrix`型で一列あるいは一行の行列である，という指定をしてください。

これまで，あるいは他の授業で学んだことのあるRのオブジェクトの形としては，`list`型が多かったのではないかと思います。`list`という形は，要素がベクトルでも数字でも文字列でもなんでもかまわない，というものでした。これを矩形(長方形)に整え，変数名としての列名や，行番号としての行名をもっているものが`data.frame`型です。`data.frame`型は`list`型の特殊系なわけです。`matrix`型は矩形のオブジェクトではありますが，`data.frame`型とは違います。`matrix`型にも列名，行名をつけることはできますが，行列であると明示してあるように，計算するときは行列演算の対象になるのです。`data.frame`型は行列の四則演算はできません。

また一点注意が必要なこととして，Rはベクトルの再利用をするということです。次の一行(`code:[code::09_02]`)を実行して中身を見てみましょう。

``` {#code::09_02 .c++ language="c++" label="code::09_02" caption="ベクトルデータの保持"}
E <- matrix(A, ncol = 3, nrow = 6)
    G <- matrix(A, ncol = 3, nrow = 4)
```

##### コード解説

1行目

:   `1:9`をオブジェクトEに代入している。ここで列数は3，行数は6を指定している。

2行目

:   `1:9`をオブジェクトGに代入している。ここで列数は3，行数は4を指定している。

::: Rscreen
ベクトルの再利用out09_02

            > E <- matrix(A, ncol = 3, nrow = 6)
            > G <- matrix(A, ncol = 3, nrow = 4)
             警告メッセージ: 
             matrix(A, ncol = 3, nrow = 4) で: 
               データ長 [9] が行数 [4] を整数で割った、もしくは掛けた値ではありません 
            > E
                 [,1] [,2] [,3]
            [1,]    1    7    4
            [2,]    2    8    5
            [3,]    3    9    6
            [4,]    4    1    7
            [5,]    5    2    8
            [6,]    6    3    9
            > G
                 [,1] [,2] [,3]
            [1,]    1    5    9
            [2,]    2    6    1
            [3,]    3    7    2
            [4,]    4    8    3
:::

オブジェクトAの要素数は9です。しかし行列$\bm{E}$を作る時に，3行6列，すなわち18の要素が必要であることを要求しました。そうするとRは(勝手にand/or親切にも？
)Aを再利用して足りないところを埋めてしまいます。今回はちょうど2回使えば埋まりましたので，エラーや警告もなくそのまま通っています。つくられた$\bm{E}$の要素を確認し，再利用されていることをみてください。ちなみに$\bm{G}$は3行4列，すなわち12の要素が必要であることを要求しました。そうするとRは警告を出して，再利用が途中で途切れますよと言ってくれます。とはいえ警告に過ぎないのでそのまま計算を続けることができ，作られた$\bm{G}$には$1,2,3,4,5,6,7,8,9,1,2,3$と2周目の最初の3要素だけ使われています[^3]。

このようにRは，可能な時には良かれと思って勝手に再利用してしまいますから，注意してくださいね。

### 行列方と行列の演算

それではRを使っての行列計算を進めましょう。

加法減法はサイズが同じでないとできない，という制約はありますが，計算記号などに違いはありません。
乗法は，スカラーとベクトル，スカラーと行列であれば普通に記述していただいて結構です。

``` {#code::09_03 .c++ language="c++" label="code::09_03" caption="ベクトルの和・差，スカラーをかける"}
x <- 1:3
y <- 8:10
x + y
x - y
2 * x
y / 3
A <- matrix(c(1, 2, 3, 4), ncol = 2)
B <- matrix(c(5, 6, 7, 8), ncol = 2)
A + B
A * 3 + B * 2
```

##### コード解説

1行目

:   `1:3`をオブジェクトxに代入している。

2行目

:   `1:9`をオブジェクトyに代入している。

3行目

:   ベクトルの和($\bm{x}+\bm{y}$)

4行目

:   ベクトルの差($\bm{x}-\bm{y}$)

5行目

:   ベクトルにスカラーをかける($2\bm{x}$)

6行目

:   ベクトルをスカラーで割る。スカラーの逆数をかけることと同じ。($\bm{y}/3$)

7行目

:   行列$\bm{A}$をつくる。サイズは$2 \times 2$

8行目

:   行列$\bm{B}$をつくる。サイズは$2 \times 2$

9行目

:   行列の和($\bm{A}+\bm{B}$)

10行目

:   行列にスカラーをかけ，それを足し合わせる。スカラー倍は各要素にかかる($3\bm{A}+2\bm{B}$)

出力結果はここでは提示しませんが，皆さんそれぞれ計算できているか確認しておいてください。

続いて行列の乗法ですが，サイズが変わるような行列としての計算の場合は特に`%*%`という記号を使うことになります。ただのアスタリスク`*`ではなく，それを`%`で囲むことで行列の積になっていることを表現しているのです。
また行列の行列を反転させるのは，という操作になりますが，これは`t()`という関数を使います。
行列の積を計算する例を`code:[code::09_03]`に示しました。計算結果が出力されますので，どういう計算をしているか一行ずつ確認しながら進めてください。

``` {#code::09_03 .c++ language="c++" label="code::09_03" caption="行列の積"}
a <- c(1, 2, 1)
b <- c(3, 4, 2)
a * b
a %*% b
a %*% t(b)
A <- matrix(1:9, ncol = 3)
A * a
A %*% a
a %*% A
B <- matrix(1:6, nrow = 3, byrow = T)
C <- matrix(c(1, 0, 0, 1, 1, 1), ncol = 3)
B %*% C
B %*% t(C)
```

##### コード解説

1行目

:   ベクトル$\bm{a}=(1,2,1)$を作る

2行目

:   ベクトル$\bm{b}=(3,4,2)$を作る

3行目

:   掛け算記号`*`を使っているが，これはベクトルの掛け算ではなく要素ごとの掛け算を意味する。

4行目

:   ベクトルの掛け算記号`%*%`を使っており，$\bm{ab}$の計算をしている。この時，ベクトル$\bm{a}$は行ベクトル，$\bm{b}$は列ベクトルと解釈されます。行列計算に適した形であり，デフォルトでは行方向が優位です。

5行目

:   ベクトルの掛け算だが`t()`で転置，すなわち$\bm{b}'$を行っており，行列に適した形に変換されて$\begin{pmatrix}1\\2\\1\end{pmatrix}\begin{pmatrix}3&4&2\end{pmatrix}$と解釈されている。$3\times1$と$1\times3$の計算なので出来上がる行列は$3\times3$のサイズになる。

6行目

:   行列$\bm{A}$を作る

7行目

:   行列$\bm{A}$に対してベクトルをかけているように見えるが，ベクトルの掛け算でなく要素の掛け算記号`*`なので，各行を1倍，2倍，1倍する結果になっている。

8行目

:   行列とベクトルの積$\bm{Aa}$であり，行列計算可能な$3\times3$と$3\times1$と解釈され，結果のサイズは$3 \times 1$になっている。

9行目

:   ベクトルと行列の積$\bm{aA}$であり，行列計算可能な$1 \times 3$と$3 \times 3$と解釈され，結果のサイズは$1 \times 3$になっている。

10-11行目

:   行列$\bm{B,C}$を作る

12行目

:   行列の積$\bm{BC}$を計算している。$3\times2$と$2\times3$の行列の積なので，結果のサイズは
    $3\times3$になっている。

13行目

:   行列の積$\bm{BC'}$を計算しようとしているが，$3\times2$と$3\times2$の積は計算できないので，エラーが返ってくる。

続いての例を見てみましょう。逆行列の計算は，手計算でやると大変なのですが，Rでは関数`solve())`を使うと計算できます。

``` {#code::09_04 .c++ language="c++" label="code::09_04" caption="逆行列の計算"}
A <- matrix(c(2,1,5,3),ncol=2)
solve(A)
A %*% solve(A)
```

##### コード解説

1行目

:   行列$\bm{A}$をつくる

2行目

:   逆行列$\bm{A}^{-1}$の計算

3行目

:   $\bm{AA^{-1}}=\bm{I}$より，逆行列になっていたことの確認。

逆行列はかけると単位行列になるので，スカラーでいうところの逆数を意味します。逆数をかけると1になるように，行列の場合は逆行列をかけると単位行列$\bm{I}$になるのでした。
これの何が嬉しいかというと，行列が連立方程式の係数を表していた場合，逆行列をかけることで連立方程式が解けるのでした($\to$
See
section[\[MatrixAndEauqtion\]](#MatrixAndEauqtion){reference-type="ref"
reference="MatrixAndEauqtion"})。
次の連立方程式を使って，実際に計算してみましょう。

$$\left \{
                    \begin{array}{lcl}
                    x-2y-5z&=&3\\
                    5x+4y+3z&=&1\\
                    3x+y-3z&=&6
                    \end{array}
                    \right .$$

``` {#code::09_05 .c++ language="c++" label="code::09_05" caption="連立方程式を解く"}
A <- matrix(c(1,5,3,-2,4,1,-5,3,-3),ncol=3)
b <- c(3,1,6)
solve(A) %*% b
```

1行目

:   係数行列$\bm{A}$をつくる

2行目

:   右辺のベクトルを作る

3行目

:   $\bm{Ax}=\bm{b}$から$\bm{A^{-1}Ax}=\bm{A^{-1}b}$より，$\bm{x}=\bm{A^{-1}}b$として方程式の解を求める

元の方程式との対応を確認しながら，「行列ってすごい，便利！」と思っていただければ幸いです。

## データの行列表現

さて連立方程式が解けるのは嬉しいのですが，データ解析に直結するかと言われたら少し違いますね。データの記述統計量など，数的処理をする時に行列を使う便利さを体感してみましょう。

::: {#tbl::09_01}
      Name        team      height     weight     salary      Win        Save
  ------------ ---------- ---------- ---------- ---------- ---------- ----------
   菅野　智之    Giants      186         92       65000        14         0
    西　勇輝     Tigers      181         82       20000        11         0
   秋山　拓巳    Tigers      188        101        3200        11         0
   大野　雄大   Dragons      183         83       13000        11         0
   石川　柊太   Softbank     185         86        4800        11         0
   千賀　滉大   Softbank     187         90       30000        11         0
   涌井　秀章    Eagles      185         85       12500        11         0
   森下　暢仁     Carp       180         76        1600        10         0
   大貫　晋一     DeNA       181         73        2500        10         0
   小川　泰弘   Swallows     171         80        9000        10         0
    $\vdots$    $\vdots$   $\vdots$   $\vdots$   $\vdots$   $\vdots$   $\vdots$

  : 投手のデータ
:::

[\[tbl::09_01\]]{#tbl::09_01 label="tbl::09_01"}

表[1.1](#tbl::09_01){reference-type="ref"
reference="tbl::09_01"}に示したのは，いつもの野球選手のデータです。それをプロジェクトフォルダに置き，`code:[code::09_05]`のコードを実行してください。

``` {#code::09_06 .c++ language="c++" label="code::09_06" caption="データファイルの読み込み"}
library(tidyverse)
dataset <- read_csv("baseballDecade.csv") %>%
  dplyr::filter(Year=="2020年度") %>% 
  dplyr::filter(position == "投手") %>%
  dplyr::select(Name, team, height, weight, salary, Win, Save) %>%
  na.omit() %>%
  arrange(-Win) %>% 
  select(height, weight, salary) %>%
  as.matrix() 
```

1行目

:   読み込み他，ファイル操作を便利にするパッケージ`tidyverse`を読み込みます[^4]。

2-9行目

:   データファイルを変形し，`dataset`オブジェクトに代入しています。ここで` \%>\% `
    はパイプ演算子と呼ばれるもので，左の操作を右の操作へつなげる役割をします。

    3行目

    :   データを2020年度のものだけに絞るため，`dplyr`パッケージの`filter`関数を適用しています。

    4行目

    :   データを投手のものだけに絞るため，`dplyr`パッケージの`filter`関数を適用しています。

    5行目

    :   変数を必要なものだけに絞るため，`dplyr`パッケージの`select`関数を適用しています。

    6行目

    :   データセットから欠損値を除いています。

    7行目

    :   表示用に，データを勝利数(変数`Win`)の多い順に並べ直しています。

    8行目

    :   以下の計算に使う変数だけに絞り込んでいます。

    9行目

    :   データセットを行列方に変換しています。

ともかくこれで`dataset`オブジェクトは行列型の，335行3列の行列になっています。
今から行う計算は，第[\[chapter7\]](#chapter7){reference-type="ref"
reference="chapter7"}章でやったように，データ行列$\bm{X}$から，平均ベクトル$\bm{m}$，平均偏差行列$\bm{V}$，分散共分散行列$\bm{S}$，標準偏差を対角に持つ行列$\bm{Q}$，標準化スコア行列$\bm{Z}$，相関行列$\bm{R}$を作る，という手順です。数式とコードを示しますので，確認しながら進めてください。

$$\label{meanM} \bm{m} = \frac{1}{n}\bm{X'1}$$
$$\label{diffV} \bm{V} = \bm{X}-\bm{1m'}$$
$$\label{covS} \bm{S} = \frac{1}{n}\bm{V'V}$$
$$\label{stdZ} \bm{Z} = \bm{VQ^{-1}}$$
$$\label{corR} \bm{R} = \frac{1}{n}\bm{Z'Z}$$

``` {#code::09_07 .c++ language="c++" label="code::09_07" caption="データの行列演算"}
n <- nrow(dataset)
one <- rep(1, n)
m <- t(dataset) %*% one / n
V <- dataset - one %*% t(m)
S <- t(V) %*% V / n
SD <- diag(S) %>% sqrt()
Q <- diag(SD)
Z <- V %*% solve(Q)
R <- t(Z) %*% Z / n
cor(dataset)
```

1行目

:   行数をオブジェクト`n`に入れる。行数を数える関数が`nrow`です。

2行目

:   データセットの列数と同じ長さの，1だけを繰り返し入れたベクトルを作ります。繰り返しは`rep`関数を使います。

3行目

:   平均ベクトル$\bm{m}$を作る操作です。数式[\[meanM\]](#meanM){reference-type="ref"
    reference="meanM"}に対応する操作です。

4行目

:   平均ベクトルを使って平均偏差行列$\bm{V}$を作る操作です。数式[\[diffV\]](#diffV){reference-type="ref"
    reference="diffV"}に対応しています。

5行目

:   分散共分散行列$\bm{S}$を作る操作です。数式[\[covS\]](#covS){reference-type="ref"
    reference="covS"}に対応しています。

6行目

:   `diag`関数を使って，行列$\bm{S}$の対角要素を抜き出し，その平方根を取り出しています。`SD`は標準偏差が入ったベクトルになります。

7行目

:   ベクトルを`diga`関数にいれると，ベクトルの要素を対角に持つ正方行列ができます。それを$\bm{Q}$として表現しています。

8行目

:   標準スコア行列$\bm{Z}$を作る操作です。平均偏差行列$\bm{V}$に$\bm{Q^{-1}}$をかけています。数式[\[stdZ\]](#stdZ){reference-type="ref"
    reference="stdZ"}に対応しています。

9行目

:   相関行列$\bm{R}$を作る操作です。数式[\[corR\]](#corR){reference-type="ref"
    reference="corR"}に対応しています。

10行目

:   出来上がった行列$\bm{R}$を検算するために，Rの持っている相関行列を作る関数`cor`を実行しています。作った$\bm{R}$と同じになっていることを確認してください。

**この一連のスクリプトは，行列のサイズが変わっても適用できます**。1つの式表現で，どんなデータサイズでも一般的に表現できているところが行列表記のすごいところです。
最終的に`cor`関数があるのなら，こんな手間をかけなくてもいいじゃないかと思うかもしれません。しかし理屈を知っていて使うことと，理屈を知らずに使うことは違いますからね。

## Rによる固有値計算

つづいて行列計算の特に面白いところ，固有値計算をしたいと思います。

固有値の計算は，小さなサイズであれば手計算でもできますが，大きなサイズになるとn次連立方程式を解くことになるのでとても大変です。解の公式で解くということもできませんので，近似計算手続きが必要です。その方法としてパワー法，ヤコビ法，ハウスホルダー法などいろいろ考えられていますが，数値計算の細かい理論に入っていくのは少し寄り道が過ぎますので割愛して，Rの関数を使って計算しましょう。

先ほど計算した相関行列$\bm{R}$を使ってこれを確認します。

``` {#code::09_08 .c++ language="c++" label="code::09_08" caption="相関行列の固有値分解"}
eig <- eigen(R)
    eig$values
    sum(eig$values)
    sum(diag(R))
    eig$vector
    eig$vector[,1]^2 %>% sum
```

固有値分解をする関数は`eigen`です。計算結果を`eig`オブジェクトに入れ，固有値`values`と固有ベクトル`vector`を表示させてみました(出力[\[RS:out09_03\]](#RS:out09_03){reference-type="ref"
reference="RS:out09_03"})。
固有値が大きい方から$1.7043160,0.9486112,0.3470728$となっています。ここでは変数が3つあって，それぞれの情報の大きさは相関行列で標準化されていて$1.0$です。この行列がもっている$3.0$の分散を，$1.7 : 0.9 : 0.3$に再分配したことになります。ちなみに固有値の総和`sum(eig$values)`は，行列のトレース` sum(diag(R))`と等しくなっていることが確認できます。

また，固有ベクトルはそれぞれの固有値に対して計算されます。各列が各固有値に対応しており，第一固有値1.7に対応する固有ベクトルは$(0.68,0.68,0.26)$です。固有ベクトルは向きだけあって大きさがありませんから，この数字はノルムすなわち二乗和したものが1になるようにして算出されているのがわかります。

::: Rscreen
固有値と固有ベクトルout09_03

        > eig <- eigen(R)
        > eig$values
        [1] 1.7043160 0.9486112 0.3470728
        > sum(eig$values)
        [1] 3
        > sum(diag(R))
        [1] 3
        > eig$vector
                  [,1]       [,2]        [,3]
        [1,] 0.6839162 -0.1734073  0.70865257
        [2,] 0.6812174 -0.1959156 -0.70537929
        [3,] 0.2611541  0.9651668 -0.01586178
        > eig$vector[,1]^2 %>% sum
        [1] 1
:::

このような数値計算を駆使して，因子分析や回帰分析が実際に計算されているのですね。
当然ですが，手計算よりも機械で計算させた方が圧倒的に早いですね。計算機の発展スピードのおかげで，今は何万，何十万というデータでも扱うことができる用意なりました。
またデータのサイズが変わってもスクリプトを変える必要がありません。

こうした原理を知っておくと，ビッグデータなど恐るるに足らず，というところではないでしょうか。

## 課題

##### 線形代数の練習問題

行列$\bm{A}=\begin{pmatrix}1 & 3 \\2 & 4\end{pmatrix},\bm{B}=\begin{pmatrix}3&1&5\\2&4&6\end{pmatrix},\bm{C}=\begin{pmatrix}4&1\\2&3\end{pmatrix}$，列ベクトル$\bm{x}=\begin{pmatrix}1\\2\\3\end{pmatrix}$,行ベクトル$\bm{y}=\begin{pmatrix}2&8\end{pmatrix}$とするとき，次の計算をRで実行するコードを書きなさい。なお，計算できないものについては「計算できない」としてコードは書かないこと。

1.  $\bm{A}+\bm{B}$

2.  $\bm{A}-\bm{C}$

3.  $\bm{AB}$

4.  $\bm{AC}$

5.  $\bm{B}'\bm{A}$

6.  $\bm{A}\bm{y}'$

7.  $\bm{xy}$

8.  $\bm{xB}$

9.  $\bm{x}'\bm{B}'$

10. $\bm{yx}$

##### 連立方程式を解く

次の連立方程式をRで解きなさい。
$$\left\{\begin{array}{rr}x-2 y+3 z= & 1 \\ 3 x+y-5 z= & -4 \\ -2 x+6 y-9 z= & -2\end{array}\right.$$

[^1]: まだだよー！という人はRStudio
    インストールといったキーワードで検索すると，親切にも案内してくれているサイトに色々出会えるでしょう。

[^2]: ExcelはMicrosoft
    Officeに含まれる表計算ソフト。NumbersはAppleのMacやiPad，iPhoneで使える表計算ソフト，CalcsはLibre
    Officeというフリーソフトウェアの表計算ソフトです。

[^3]: そんなことよりオブジェクトがA,B,CときてるんだからEのつぎはFだろ，と思う人もいるかもしれません。Fでもいいのですが，実は大文字の`F`と`T`はそれぞれ`FALSE/TRUE`の略語であり予約後語です。上書きして使うこともできますが，なるべく避けたほうがいいでしょう。ちなみにRStudioなどでこれら一文字を使うと予約語になっているので表示の時にハイライトされます。

[^4]: `tidyverse`パッケージがない人はインストールしてください。関連パッケージをいろいろまとめたパッケージ群パッケージなので，少し時間がかかります。
